Okay, I was able to record and upload (at least I got a success toast message - have not yet confirmed by checking in the firestore database); I am not able to access the previous recorded videos - Console Error
Error: data.createdAt?.toDate is not a function

src/lib/firebase/firestore.ts (87:51) @ <unknown>

  85 |         id: doc.id,
  86 |         ...data,
> 87 |         createdAt: (data.createdAt as Timestamp)?.toDate().toISOString() || new Date().toISOString(),
     |                                                   ^
  88 |        } as VideoMeta);
  89 |     });
  90 |     return videos;
Call Stack
12

Show 9 ignore-listed frame(s)
<unknown>
src/lib/firebase/firestore.ts (87:51)
getAllVideos
src/lib/firebase/firestore.ts (82:19)
async VideosPage.useEffect.fetchVideos
src/app/(authenticated)/videos/page.tsx (21:31)
Not only do I want to access them, but as the admin I would like to be able to delete, edit, share, and modify in other ways - we need to be able to fetch the videos and show them in the appropriate places