The message I can see is 'User does not have permission to access ....'' but this should not be the case because I was able to upload the video from my window's laptop - so the Firebase rules cannot be the issue - please check on other areas of the code for this error: Console Error
FirebaseError: (https://nextjs.org/docs/app/building-your-application/configuring/debugging#server-side-code) Firebase Storage: User does not have permission to access 'videos/drDKPvuWlVPdqTJnm4wLUxyFsHJ3/ios_uploads/test_video_2nd_june_2025_1748833105151.mp4'. (storage/unauthorized)

Call Stack8Hide 8 ignore-listed frame(s)

FirebaseErrornode_modules/@firebase/util/src/errors.ts (85:10)
StorageErrornode_modules/@firebase/storage/src/implementation/error.ts (40:10)
unauthorizednode_modules/@firebase/storage/src/implementation/error.ts (175:26)
errorHandlernode_modules/@firebase/storage/src/implementation/requests.ts (123:32)
backoffDonenode_modules/@firebase/storage/src/implementation/request.ts (173:39)
triggerCallbacknode_modules/@firebase/storage/src/implementation/backoff.ts (67:30)
responseHandlernode_modules/@firebase/storage/src/implementation/backoff.ts (91:27)
<unknown>node_modules/@firebase/storage/src/implementation/request.ts (142:26)
Was this helpful? (https://nextjs.org/telemetry#error-feedback)